version: '3.3'
services:
  vault:
    image: 10.1.20.108:8087/hashicorp/vault
    container_name: vault
    environment:
      VAULT_ADDR: "http://10.1.20.200:8200"
      VAULT_API_ADDR: "http://10.1.20.200:8200"
      VAULT_ADDRESS: "http://10.1.20.200:8200"
    ports:
      - "8200:8200"
      - "8201:8201"
    restart: always
    volumes:
      - ./logs:/vault/logs/:rw
      - ./data:/vault/data/:rw
      - ./config:/vault/config/:rw
      - ./key:/vault/key/:rw
      - ./file:/vault/file/:rw
      - ./auto_init.sh:/vault/auto_init.sh:rw
    cap_add:
      - IPC_LOCK
    entrypoint: sh /vault/auto_init.sh
