version: '3.3'
services:
  vault:
    image: hashicorp/vault
    container_name: vault-transit
    ports:
      - "8200:8200"
      - "8201:8201"
    restart: always
    volumes:
      - ./logs:/vault/logs/:rw
      - ./data:/vault/data/:rw
      - ./config:/vault/config/:rw
      - ./key:/vault/key/:rw
      - ./auto_unseal.sh:/vault/auto_unseal.sh:rw
    cap_add:
      - IPC_LOCK
    entrypoint: sh /vault/auto_unseal.sh
